### PR TITLE
feat: add Ruby quickstart

### LINKED ISSUE #373: Please add Ruby as a quickstart
Straight forward request (hopefully). Please include Ruby as a quickstart. (And maybe Crystal, too?)

### PR DESCRIPTION
**Pull request by Aunali321**
Closes #373 
image

DevPod uses microsoft/vscode-try-remote-* images for quickstart guides.  But Microsoft does not provide any images for Ruby. So i made my own image https://github.com/Aunali321/ruby-quickstarter-template for this PR. I recommend DevPod team to fork the image to `loft-sh` repo so you don't have to be dependent on me.

### CODE REVIEW

**Comment by pascalbreuninger** [comment]
Hi @Aunali321, thanks for your PR!
I'm not a fan of how it looks now, would need to revisit it. What do you think of having a `more` popover where we can show other quickstarts?
This way we keep the original first party supported quickstarts but also allow for community contributions

**Comment by Aunali321** [comment]
> Hi @Aunali321, thanks for your PR! I'm not a fan of how it looks now, would need to revisit it. What do you think of having a `more` popover where we can show other quickstarts? This way we keep the original first party supported quickstarts but also allow for community contributions

Yup that sounds much better. Will be done later today.

**Comment by Aunali321** [comment]
image
image

Is this fine?

**Comment by pascalbreuninger** [comment]
Definitely better. I took the liberty to adjust it a bit:
image

If you're okay with degrading .net to community and reusing the community icon I'll merge it

**Comment by Aunali321** [comment]
Looks good to me

**Comment by Aunali321** [comment]
Can you add hacktoberfest accepted label?

**Comment by pascalbreuninger** [comment]
sure thing ;)

**Comment by Aunali321** [comment]
> sure thing ;)

It's not being picked up by hacktoberfest website. I am pretty sure it needs to be `hacktoberfest-accepted` label

**Comment by pascalbreuninger** [comment]
Ah wasn't aware of that, updated

**Pull request merged**
