### PR TITLE
fix issue 292, where find container failed when using podman

### PR DESCRIPTION
**Pull request by pleclech**
Fixing issue #292:
Modifying FindDevContainer to only search by the ID and not ID+metadata.

### CODE REVIEW

**Comment by FabianKramm** [comment]
@pleclech thanks for the PR! Not sure if that is exactly what we want, as this is omitting the metadata check completely, what is the exact problem with podman and the metadata label?

**Comment by pleclech** [comment]
> @pleclech thanks for the PR! Not sure if that is exactly what we want, as this is omitting the metadata check completely, what is the exact problem with podman and the metadata label?

Hello @FabianKramm ,
The problem is described in  #292, but for short podman filter failed badly with the format of the metadata and so no container can be retrieved
```
find container: Error: invalid argument "label=devcontainer.metadata=[{\"id\":\"ghcr.io/devcontainers/features/common-utils:2\"},{\"id\":\"./local-features/apache-config\"},{\"id\":\"ghcr.io/devcontainers/features/node:1\",\"customizations\":{\"vscode\":{\"extensions\":[\"dbaeumer.vscode-eslint\"]}}},{\"id\":\"ghcr.io/devcontainers/features/git:1\"},{\"remoteUser\":\"vscode\",\"customizations\":{\"vscode\":{\"extensions\":[\"xdebug.php-debug\",\"bmewburn.vscode-intelephense-client\",\"mrmlnc.vscode-apache\"],\"settings\":{\"php.validate.executablePath\":\"/usr/local/bin/php\"}}}},{\"customizations\":{\"vscode\":{\"extensions\":[\"streetsidesoftware.code-spell-checker\"],\"settings\":{}}}}]" for "-f, --filter" flag: parse error on line 1, column 31: bare " in non-quoted-field
See 'podman ps --help'
```
If you go back the second time , it will work because the first time  [you check if the container exists but only by ID](https://github.com/loft-sh/devpod/blob/b94eb4ae2afeb5e4e1e1c7e93336f89caed182dc/pkg/devcontainer/single.go#L15), and [then exit if so](https://github.com/loft-sh/devpod/blob/b94eb4ae2afeb5e4e1e1c7e93336f89caed182dc/pkg/devcontainer/single.go#L15).
I think it make sense since ID is unique and adding metadata in the filter for searching will not add any more value ?

What do you think ?

**Comment by 89luca89** [comment]
Hi @pleclech 
I've implemented another PR #338 which works around the label thing (which seems to be a podman upstream problem) using b64 encoding, additionally it implements some other rootless podman fixes :+1:

**Comment by 89luca89** [comment]
> > Hi @pleclech I've implemented another PR #338 which works around the label thing (which seems to be a podman upstream problem) using b64 encoding, additionally it implements some other rootless podman fixes +1
> 
> Hi @89luca89 I tried to pull your PR and build it, but i can't because of this error: `pkg/devcontainer/setup/setup.go:39:55: undefined: syscall.Stat_t` as `syscall.Stat_t` is Linux only

Hi @pleclech where are running podman from?
Technically that check (the stat one) should be performed inside the container, which is linux

**Comment by pleclech** [comment]
> > > Hi @pleclech I've implemented another PR #338 which works around the label thing (which seems to be a podman upstream problem) using b64 encoding, additionally it implements some other rootless podman fixes +1
> > 
> > 
> > Hi @89luca89 I tried to pull your PR and build it, but i can't because of this error: `pkg/devcontainer/setup/setup.go:39:55: undefined: syscall.Stat_t` as `syscall.Stat_t` is Linux only
> 
> Hi @pleclech where are running podman from? Technically that check (the stat one) should be performed inside the container, which is linux

At compile time, and if i look in the test directory i don't see any cli for windows being built

**Comment by 89luca89** [comment]
I've removed that part for now, can you try again?

**Comment by pleclech** [comment]
> I've removed that part for now, can you try again?

The build succeed. And podman does not complain for the filter

**Pull request closed without merging**
