### PR TITLE
chore: update IDE versions

### PR DESCRIPTION
**Pull request by shanman190**

### CODE REVIEW

**Review by pascalbreuninger — APPROVED** [review]
LGTM, thanks for the PR

**Comment by shanman190** [comment]
@pascalbreuninger, something else that I was wondering too with respect to this. Would you all be open the the virtual urls like was done for fleet?

https://github.com/loft-sh/devpod/blob/main/pkg%2Fide%2Ffleet%2Ffleet.go#L34-L45

This would enable always ensuring that DevPod is downloading the latest available JetBrains UI when it is provisioning a workspace.

**Comment by pascalbreuninger** [comment]
@shanman190 of course, it just hasn't been a big enough problem for us yet. If you're willing to open a PR we'd be happy to merge that

**Comment by RobinQu** [comment]
When will this go into next release then?

**Comment by pascalbreuninger** [comment]
@RobinQu I'd wait 1-2 weeks because the 2024.1 updates are pretty new still

**Comment by shanman190** [comment]
@pascalbreuninger, I've created https://github.com/loft-sh/devpod/pull/1006 like we discussed earlier.

**Comment by nojaf** [comment]
Is this available in any alpha?

**Comment by pascalbreuninger** [comment]
@nojaf yes, should be in the latest one

**Comment by shanman190** [comment]
@nojaf, the very latest alpha should download the latest version by default. Then you can set the version explicitly as well to choose an alternative version.

**Pull request merged**
