### PR TITLE
add environment variable substitution in tar gz feature ids

### PR DESCRIPTION
**Pull request by aacebedo**
This PR add the substitution of environment variables in feature id of direct tar features
It enables using private gitlab registries to house feature easily

### CODE REVIEW

**Comment by aacebedo** [comment]
corrected the lint errors

**Comment by 89luca89** [comment]
Hi @aacebedo 

Thanks for the PR!
We'll discuss internally about this, as for now this is diverging from the standard reference of devcontainer: https://containers.dev/implementors/json_reference/

We'll also follow the discussion in the upstream that you opened

**Comment by aacebedo** [comment]
I did not receive an answer on the other thread yet but I think I can solve this by adding the http headers to use in the devpod customization field. This way it won't diverge from the spec. What do you think?

**Comment by 89luca89** [comment]
@aacebedo Yes if it's part of the customization then it can work :+1: so that if in the future upstream wants to support this, we'll not be out of spec

**Comment by aacebedo** [comment]
I close this in favor of #715

**Pull request closed without merging**
